version: "3.7"

volumes:
  portainer_data:
networks:
  lan:

services:
  portainer:
    image: portainer/portainer
    volumes:
      - type: volume
        source: portainer_data
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "9000:9000"
    deploy:
      # replicas: 1
      # placement:
      #   constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    command: --host=unix:///var/run/docker.sock
  note_db:
    image: neo4j:latest
    networks:
      - lan
    environment:
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
    ports:
      - "7474:7474"
      - "6477:6477"
      - "7687:7687"
    volumes:
      - type: bind
        source: ~/neo4j/data
        target: /data
      - type: bind
        source: ~/neo4j/logs
        target: /logs
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 120M
      restart_policy:
        condition: on-failure
